import com.example.demo.PaymentOffer

rule "Offer for Paytm"
	when 
		offerObject: PaymentOffer(channel=="paytm")
	then
		offerObject.setDiscount(17.0);
	end
rule "Offer for PhonePe"
	when 
		offerObject: PaymentOffer(channel=="phonepe")
	then
		offerObject.setDiscount(20.0);
	end
rule "Offer for GooglePay"
	when 
		offerObject: PaymentOffer(channel=="googlepay")
	then
		offerObject.setDiscount(25.0);
	end